### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'write' - breaks execution 

### ISSUE THREAD

**Issue by mdgis** [datakind/idi-datadive-2018#53]
Hey guys just tried running it locally from my computer with one search term "China Construction Bank" and when it got to the FMO scraper it the threw an unhandled error and then landed on a **Internal Server Error** page.  Traceback is below.  Let me know if i can be of help with this. 

THANK YOU !!!
---

Scraping: FMO
Initializing Website
searching for term
https://www.fmo.nl/worldmap?search=%22China+Construction+Bank%22&region=&year=&projects=allProjects
Scraping Results

Processing Page: 1 

Completed Search for China Construction Bank 

/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [03:00<00:00, 180.36s/it]
[2018-07-16 11:41:34,255] ERROR in app: Exception on /run [POST]
Traceback (most recent call last):
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/GoogleDrive/My Drive/Dowd_Local/June_2018_DD_Gits/idi-datadive-2018/flask_scraper_demo/app/routes.py", line 83, in run_scraper
    table_builder.save_df()
  File "/Volumes/GoogleDrive/My Drive/Dowd_Local/June_2018_DD_Gits/idi-datadive-2018/flask_scraper_demo/app/table_builder.py", line 32, in save_df
    writer.save()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/pandas/io/excel.py", line 1732, in save
    return self.book.close()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 311, in close
    self._store_workbook()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 658, in _store_workbook
    xlsx_file.write(os_filename, xml_filename)
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/zipfile.py", line 1488, in write
    self.fp.write(zinfo.FileHeader(zip64))
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/zipfile.py", line 680, in write
    n = self.fp.write(data)
AttributeError: 'PosixPath' object has no attribute 'write'
2018-07-16 11:41:34,255 - app - ERROR - Exception on /run [POST]
Traceback (most recent call last):
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/GoogleDrive/My Drive/Dowd_Local/June_2018_DD_Gits/idi-datadive-2018/flask_scraper_demo/app/routes.py", line 83, in run_scraper
    table_builder.save_df()
  File "/Volumes/GoogleDrive/My Drive/Dowd_Local/June_2018_DD_Gits/idi-datadive-2018/flask_scraper_demo/app/table_builder.py", line 32, in save_df
    writer.save()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/pandas/io/excel.py", line 1732, in save
    return self.book.close()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 311, in close
    self._store_workbook()
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 658, in _store_workbook
    xlsx_file.write(os_filename, xml_filename)
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/zipfile.py", line 1488, in write
    self.fp.write(zinfo.FileHeader(zip64))
  File "/Users/michaeldowd/anaconda/envs/my_py_3/lib/python3.5/zipfile.py", line 680, in write
    n = self.fp.write(data)
AttributeError: 'PosixPath' object has no attribute 'write'
2018-07-16 11:41:34,266 - werkzeug - INFO - 127.0.0.1 - - [16/Jul/2018 11:41:34] "POST /run HTTP/1.1" 500 -

**Comment by jimjshields** [comment]
Awesome, thanks @xtream1101!! I can merge.
